PERMANENT_COMMITTEE_NAMES = {
    0: 'Comissão de Agricultura, Pecuária, Abastecimento e Desenvolvimento Rural',
    1: 'Comissão de Ciência e Tecnologia, Comunicação e Informática',
    2: 'Comissão de Constituição e Justiça e de Cidadania',
    3: 'Comissão de Cultura',
    4: 'Comissão de Defesa do Consumidor',
    5: 'Comissão de Desenvolvimento Econômico, Indústria, Comércio e Serviços',
    6: 'Comissão de Desenvolvimento Urbano',
    7: 'Comissão de Direitos Humanos e Minorias',
    8: 'Comissão de Educação',
    9: 'Comissão de Finanças e Tributação',
    10: 'Comissão de Fiscalização Financeira e Controle',
    11: 'Comissão de Integração Nacional, Desenvolvimento Regional e Amazônia',
    12: 'Comissão de Legislação Participativa',
    13: 'Comissão de Meio Ambiente e Desenvolvimento Sustentável',
    14: 'Comissão de Minas e Energia',
    15: 'Comissão de Relações Exteriores e de Defesa Nacional',
    16: 'Comissão de Segurança Pública e Combate ao Crime Organizado',
    17: 'Comissão de Seguridade Social e Família',
    18: 'Comissão de Trabalho, Administração e Serviço Público',
    19: 'Comissão de Turismo',
    20: 'Comissão de Viação e Transportes',
    21: 'Comissão do Esporte',
    22: 'Comissão dos Direitos da Mulher',
    23: 'Comissão dos Direitos da Pessoa Idosa',
    24: 'Comissão dos Direitos das Pessoas com Deficiência'
}

WRONG_COMMITTEE_NAMES = {
    'Comissão da Amazônia e de Desenvolvimento Regional': 11,
    'Comissão da Amazônia, Integração Nacional e de Desenvolvimento Regional': 11,
    'Comissão de Agricultura e Política Rural': 0,
    'Comissão de Constituição e Justiça e de Redação': 2,
    'Comissão de Defesa dos Direitos da Mulher': 22,
    'Comissão de Defesa dos Direitos da Pessoa Idosa': 23,
    'Comissão de Defesa dos Direitos das Pessoas com Deficiência': 24,
    'Comissão de Desenvolvimento Econômico, Indústria e Comércio': 5,
    'Comissão de Desenvolvimento Urbano e Interior': 6,
    'Comissão de Direitos Humanos': 7,
    'Comissão de Economia, Indústria e Comércio': 5,
    'Comissão de Educação': 8,
    'Comissão de Educação e Cultura': 3,
    'Comissão de Educação, Cultura e Desporto': 3,
    'Comissão de Integração Nacional, Desenvolvimento Regional e da Amazônia': 11,
    'Comissão de Turismo e Desporto': 19,
    'Comissão de Trabalho, de Administração e Serviço Público': 18,
    'Secretaria da Mulher': 22,
}

COMMITTEE_CATEGORY_PATTERNS = {
    'Comissão Especial': 'Comissão Especial',
    'Comissão Externa': 'Comissão Externa',
    'Comissão Mista': 'Comissão Mista',
    'Mista de': 'Comissão Mista',
    'Comissão Parlamentar de Inquérito': 'Comissão de Inquérito',
    'CPI -': 'Comissão de Inquérito',
    'CPMI -': 'Comissão de Inquérito',
    'Conjunta -': 'Conjunta de Comissões',
    'Subcomissão': 'Subcomissão',
    'Sub.': 'Subcomissão'
}
